Updated SEMCOG Example
ActivitySim/activitysim pull request #603
Opened 2022-09-13 23:06 UTC by dhensle

Pull request includes the following updates from the previous SEMCOG version:
* Conversion from 1-zone to 2-zone
* Inclusion of University of Michigan related models
* Moved to 48 half-hour time periods
* Re-estimated models including auto ownership, location & destination choice, tour scheduling
* Various model calibrations

2022-09-14 23:14 UTC, dhensle commented
This pull request accompanies the [pull request in the ActivitySim/activitysim_resources](https://github.com/ActivitySim/activitysim_resources/pull/27) containing the full model data.  

- [ ] The links to data in the example_manifest.yaml in this pull request need to be set after merging the pull request containing the data.

2023-05-12 15:01 UTC, jpn-- requested changes
I made some suggestions to clean up. Only one substantive note on use of parenthesis that will potentially have impact on the model numerically in some cases.  To be consistent with our naming conventions, I think this should now be called "production_semcog" (and many congratulations to all involved for being the first to get there).

2023-05-12 15:01 UTC, jpn-- commented on activitysim/examples/example_semcog/configs/annotate_households.csv
> +#,income,households.hincp * households.adjinc/100000
Can we clean up this code?  I understand how this happens, I do it too, but it looks like this PR is adding all new commented-out lines of code that someone tried and didn't like but didn't actually delete.

2023-05-12 15:01 UTC, jpn-- commented on .github/workflows/core_tests.yml
> +          - example_semcog
We changed the [system of names of the examples](https://activitysim.github.io/activitysim/v1.2.0/examples.html?highlight=placeholder#examples) to be prefixed with "placeholder", "prototype", or "production".  Seems like we want this one to be `production_semcog` now, not `example_semcog`?

2023-05-12 15:01 UTC, jpn-- commented on activitysim/examples/example_semcog/configs/annotate_persons_cdap.csv
> +#,cdap_activity,"np.where((persons.work_from_home) & (persons.cdap_activity=='M'), np.random.choice(['N','H']), persons.cdap_activity)"
Delete line instead of comment out?

2023-05-12 15:01 UTC, jpn-- commented on activitysim/examples/example_semcog/configs/annotate_persons_school.csv
> +#,home_county,"reindex(land_use.COUNTY, persons.home_zone_id)"
Delete line instead of comment out?

2023-05-12 15:01 UTC, jpn-- commented on activitysim/examples/example_semcog/configs/annotate_persons_workplace.csv
> +#,umich_affiliate,"df.get(umich_worker, default=False) | df.get(umich_student, default=False)"
Delete line instead of comment out?

2023-05-12 15:01 UTC, jpn-- commented on activitysim/examples/example_semcog/configs/atwork_subtour_frequency.csv
> +util_zero_cars_owned_by_hh_dummy, auto_ownership == 0,coefficient_zero_cars_owned_by_hh_dummy_no_subtours,coefficient_zero_cars_owned_by_hh_dummy_eat,coefficient_zero_cars_owned_by_hh_dummy_business1
Is this just adding a space in front of the expression?  Does that do anything important?

2023-05-12 15:01 UTC, jpn-- commented on activitysim/examples/example_semcog/configs/auto_ownership_coeffs_.csv
> +coefficient_name,value,constrain
We sees to have two different auto ownership coeffs files (one with an underscore suffix) are both required or is one a commit accident?

2023-05-12 15:01 UTC, jpn-- commented on activitysim/examples/example_semcog/configs/mandatory_tour_frequency.csv
> +util_can_walk_to_work_or_school_ft,Can walk to work or school - Full-time worker interaction,(ptype == 1) & (distance_to_work < 3 | distance_to_school < 3),,,,,coef_can_walk_to_work_and_school
PR strips the parenthesis.  I believe they are important, as the pipe operator (bitwise or) has precedence over less-than operator in some contexts (sharrow and/or not-sharrow, I forget).  So "3 | distance_to_school" is evaluated first, then that must be greater than distance to work and less than 3, which is not what we want.

2023-05-12 15:01 UTC, jpn-- commented on activitysim/examples/example_semcog/configs/tour_mode_choice.yaml
> +    # valueOfTime: 8.00
just delete constants we don't want

2023-05-12 20:29 UTC, aletzdy commented on activitysim/examples/example_semcog/configs/annotate_households.csv
> +#,income,households.hincp * households.adjinc/100000
cleaned up.

2023-05-12 20:29 UTC, aletzdy commented on .github/workflows/core_tests.yml
> +          - example_semcog
agreed. renamed all instances to production_semcog.

2023-05-12 20:29 UTC, aletzdy commented on activitysim/examples/example_semcog/configs/annotate_persons_cdap.csv
> +#,cdap_activity,"np.where((persons.work_from_home) & (persons.cdap_activity=='M'), np.random.choice(['N','H']), persons.cdap_activity)"
cleaned up.

2023-05-12 20:29 UTC, aletzdy commented on activitysim/examples/example_semcog/configs/annotate_persons_school.csv
> +#,home_county,"reindex(land_use.COUNTY, persons.home_zone_id)"
cleaned up.

2023-05-12 20:29 UTC, aletzdy commented on activitysim/examples/example_semcog/configs/annotate_persons_workplace.csv
> +#,umich_affiliate,"df.get(umich_worker, default=False) | df.get(umich_student, default=False)"
cleaned up.

2023-05-12 20:29 UTC, aletzdy commented on activitysim/examples/example_semcog/configs/atwork_subtour_frequency.csv
> +util_zero_cars_owned_by_hh_dummy, auto_ownership == 0,coefficient_zero_cars_owned_by_hh_dummy_no_subtours,coefficient_zero_cars_owned_by_hh_dummy_eat,coefficient_zero_cars_owned_by_hh_dummy_business1
no. probably just an accidental stroke of the space bar! cleaned up.

2023-05-12 20:29 UTC, aletzdy commented on activitysim/examples/example_semcog/configs/auto_ownership_coeffs_.csv
> +coefficient_name,value,constrain
old file. deleted.

2023-05-12 20:29 UTC, aletzdy commented on activitysim/examples/example_semcog/configs/mandatory_tour_frequency.csv
> +util_can_walk_to_work_or_school_ft,Can walk to work or school - Full-time worker interaction,(ptype == 1) & (distance_to_work < 3 | distance_to_school < 3),,,,,coef_can_walk_to_work_and_school
thanks for bringing this to our attention. fixed and SEMCOG code updated.

2023-05-12 20:29 UTC, aletzdy commented on activitysim/examples/example_semcog/configs/tour_mode_choice.yaml
> +    # valueOfTime: 8.00
cleaned up.

2023-05-15 18:54 UTC, aletzdy commented
all review comments are responded to and incorporated, and the PR is ready. Thanks, Jeff!

2023-05-16 16:01 UTC, jpn-- commented on .gitignore
> +activitysim/examples/example_semcog/configs_mp/settings.yaml
oops?

2023-05-16 16:01 UTC, jpn-- commented on .vscode/settings.json
> +}
we don't want to introduce a .vscode directory... maybe we want one, and/or .idea, but not as part of this PR

2023-05-16 16:01 UTC, jpn-- commented on activitysim/examples/example_manifest.yaml
> +    - cc/media/activitysim/activitysim_resources/master/sandag_xborder/traffic_skims_xborder_MD.omx
oops?

2023-05-16 16:01 UTC, jpn-- commented on activitysim/examples/production_semcog/test/output/cache/chunk_cache.csv
> +tag,num_rows,rss,uss,bytes,uss_row_size,hybrid_uss_row_size,bytes_row_size
this is a chunk cache from the test data?  or from the full size data?

2023-05-16 18:38 UTC, aletzdy commented on .gitignore
> +activitysim/examples/example_semcog/configs_mp/settings.yaml
fixed.

2023-05-16 18:38 UTC, aletzdy commented on .vscode/settings.json
> +}
fixed.

2023-05-16 18:38 UTC, aletzdy commented on activitysim/examples/example_manifest.yaml
> +    - cc/media/activitysim/activitysim_resources/master/sandag_xborder/traffic_skims_xborder_MD.omx
fixed.

2023-05-16 18:38 UTC, aletzdy commented on activitysim/examples/production_semcog/test/output/cache/chunk_cache.csv
> +tag,num_rows,rss,uss,bytes,uss_row_size,hybrid_uss_row_size,bytes_row_size
took out the cache file. it was a cache file for the test data which is not needed.

2023-05-16 21:06 UTC, aletzdy commented
Responded to review comments and fixed issues. Thank you, Jeff.

2023-05-19 20:10 UTC, merged