BayDAG Contribution #2: Enhanced Disaggregate Accessibility Merging
ActivitySim/activitysim pull request #768
Opened 2023-12-18 18:31 UTC by dhensle

This pull request gives the user greater flexibility to join disaggregate accessibilities to the households / person tables. The original design for the model just joined the disaggregate accessibilities to the household table by a set of auto ownership and home zone.  This was insufficient for the purpose of joining all auto ownership levels created in the disaggregate accessibilities model so they could be applied to the alternatives in the auto ownership model.  

See the SANDAG ABM3 configs for an example implementation: [yaml](https://github.com/SANDAG/ABM/blob/ABM3_develop/src/asim/configs/resident/disaggregate_accessibility.yaml#L120) and [annotator](https://github.com/SANDAG/ABM/blob/ABM3_develop/src/asim/configs/resident/annotate_disaggregate_accessibility.csv).

Required for SANDAG ABM3 production? -- yes

2023-12-22 15:37 UTC, AndrewTheTM commented
Just commenting to say that these are necessary for Met Council's Phase 2 ActivitySim model. 

cc: @JonathanEhrlichMC, @dvfarmer

2024-03-19 15:05 UTC, i-am-sijia approved these changes

2024-03-19 16:23 UTC, jpn-- commented
This non-trivial PR has no testing to confirm it works.

2024-03-26 00:57 UTC, jpn-- requested changes

2024-03-26 00:57 UTC, jpn-- commented on activitysim/abm/models/disaggregate_accessibility.py
> +
This PR actually adds two things to DisaggregateAccessibilitySettings, we also need to add something like this...

```
    KEEP_COLS: list[str] | None = None
    """
    Columns to keep in the proto-population tables after generation.

    If None, all columns that have names containing the word ""accessibility" are kept.
    """
```

2024-03-26 00:57 UTC, jpn-- commented on activitysim/abm/tables/disaggregate_accessibility.py
> +    keep_cols = model_settings.get("KEEP_COLS", accessibility_cols)
This should be something like:
```
    if model_settings.KEEP_COLS is None:
        keep_cols = [x for x in proto_accessibility_df.columns if "accessibility" in x]
    else:
        keep_cols = model_settings.KEEP_COLS
```

2024-03-28 15:21 UTC, jpn-- approved these changes

2024-03-28 15:22 UTC, merged